import streamlit as st
import joblib
import sqlite3
import pandas as pd
from fpdf import FPDF
from io import BytesIO
import plotly.express as px
from datetime import datetime
import random

st.set_page_config(page_title="CSAT AI Dashboard", page_icon="📊", layout="wide")

# ---------------- LOGIN ----------------

if "logged_in" not in st.session_state:
    st.session_state.logged_in = False

if not st.session_state.logged_in:
    st.title("🔐 CSAT System Login")

    col1, col2, col3 = st.columns([1,2,1])

    with col2:
        username = st.text_input("Username")
        password = st.text_input("Password", type="password")

        if st.button("Login"):
            if username == "admin" and password == "admin123":
                st.session_state.logged_in = True
                st.rerun()
            else:
                st.error("Invalid credentials")

    st.stop()

# ---------------- LOAD MODEL ----------------

model = joblib.load("csat_model.pkl")

# ---------------- DATABASE ----------------

conn = sqlite3.connect("csat_history.db", check_same_thread=False)
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS predictions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
response_time INTEGER,
agent_friendliness INTEGER,
issue_resolution INTEGER,
call_duration INTEGER,
customer_effort INTEGER,
product_satisfaction INTEGER,
support_knowledge INTEGER,
followup_quality INTEGER,
complaint_handling INTEGER,
first_call_resolution INTEGER,
waiting_time INTEGER,
customer_mood INTEGER,
service_quality INTEGER,
predicted_csat INTEGER
)
""")

conn.commit()

df = pd.read_sql_query("SELECT * FROM predictions", conn)

# ---------------- FEATURES ----------------

feature_names = [
"Response Time","Agent Friendliness","Issue Resolution Quality","Call Duration",
"Customer Effort Score","Product Satisfaction","Support Knowledge",
"Follow-up Quality","Complaint Handling","First Call Resolution",
"Waiting Time","Customer Mood","Service Quality"
]

# ---------------- PDF GENERATOR ----------------

def generate_pdf(prediction, features):

    pdf = FPDF()
    pdf.add_page()

    pdf.set_fill_color(0,102,204)
    pdf.set_text_color(255,255,255)
    pdf.set_font("Arial","B",16)
    pdf.cell(0,15,"CSAT AI Analytics Report",0,1,"C",True)

    pdf.ln(5)

    pdf.set_text_color(0,0,0)
    pdf.set_font("Arial","",11)

    report_id = random.randint(10000,99999)
    date = datetime.now().strftime("%d-%m-%Y %H:%M")

    pdf.cell(100,8,f"Report ID: {report_id}",0,0)
    pdf.cell(0,8,f"Date: {date}",0,1)

    pdf.ln(5)

    pdf.set_font("Arial","B",12)
    pdf.cell(0,10,"Customer Support Metrics",0,1)

    pdf.set_fill_color(230,230,230)
    pdf.cell(120,8,"Feature",1,0,"C",True)
    pdf.cell(40,8,"Score",1,1,"C",True)

    pdf.set_font("Arial","",11)

    for name,value in zip(feature_names,features):
        pdf.cell(120,8,name,1)
        pdf.cell(40,8,str(value),1,1,"C")

    pdf.ln(10)

    pdf.set_font("Arial","B",14)

    if prediction >= 4:
        pdf.set_fill_color(46,204,113)
        text = f"High Customer Satisfaction: {prediction}"
    elif prediction == 3:
        pdf.set_fill_color(241,196,15)
        text = f"Moderate Customer Satisfaction: {prediction}"
    else:
        pdf.set_fill_color(231,76,60)
        text = f"Low Customer Satisfaction: {prediction}"

    pdf.cell(0,12,text,0,1,"C",True)

    pdf.ln(10)

    pdf.set_font("Arial","B",12)
    pdf.cell(0,8,"AI Insights",0,1)

    pdf.set_font("Arial","",11)
    pdf.multi_cell(
        0,7,
        "This CSAT prediction was generated using a machine learning model "
        "trained on customer support performance metrics such as response time, "
        "resolution quality and service experience."
    )

    pdf.ln(10)

    pdf.set_font("Arial","I",10)
    pdf.set_text_color(120,120,120)
    pdf.cell(0,8,"Generated by CSAT AI Dashboard",0,1,"C")

    pdf.output("csat_report.pdf")

# ---------------- SIDEBAR ----------------

st.sidebar.title("📊 CSAT Dashboard")

menu = st.sidebar.radio(
    "Navigation",
    ["Dashboard","Predict CSAT","Analytics","Reports"]
)

# ---------------- DASHBOARD ----------------

if menu == "Dashboard":

    st.title("Customer Satisfaction Dashboard")

    if df.empty:
        st.info("No data available yet. Go to 'Predict CSAT' to generate predictions.")

    else:

        col1,col2,col3 = st.columns(3)

        col1.metric("Total Predictions",len(df))
        col2.metric("Average CSAT",round(df["predicted_csat"].mean(),2))
        col3.metric("Max CSAT",df["predicted_csat"].max())

        st.divider()

        fig = px.histogram(
            df,
            x="predicted_csat",
            color="predicted_csat",
            title="CSAT Distribution"
        )

        st.plotly_chart(fig,use_container_width=True)

# ---------------- PREDICT ----------------

if menu == "Predict CSAT":

    st.title("Predict Customer Satisfaction")

    col1,col2 = st.columns(2)

    features = []

    with col1:
        for i in range(7):
            features.append(st.slider(feature_names[i],0,10,5))

    with col2:
        for i in range(7,13):
            features.append(st.slider(feature_names[i],0,10,5))

    if st.button("Predict CSAT Score"):

        prediction = model.predict([features])[0]

        cursor.execute("""
        INSERT INTO predictions VALUES(NULL,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """,(*features,int(prediction)))

        conn.commit()

        if prediction >= 4:
            st.success(f"😊 High Satisfaction: {prediction}")
        elif prediction == 3:
            st.warning(f"⚠️ Moderate Satisfaction: {prediction}")
        else:
            st.error(f"❌ Low Satisfaction: {prediction}")

        generate_pdf(prediction,features)

        with open("csat_report.pdf","rb") as f:
            st.download_button("Download PDF Report",f,"csat_report.pdf")

# ---------------- ANALYTICS ----------------

if menu == "Analytics":

    st.title("Advanced Analytics")

    col1,col2 = st.columns(2)

    with col1:

        if not df.empty:
            fig = px.histogram(df,x="predicted_csat",color="predicted_csat")
            st.plotly_chart(fig,use_container_width=True)

    with col2:

        importance_df = pd.DataFrame({
            "Feature":feature_names,
            "Importance":model.feature_importances_
        }).sort_values(by="Importance")

        fig = px.bar(
            importance_df,
            x="Importance",
            y="Feature",
            orientation="h"
        )

        st.plotly_chart(fig,use_container_width=True)

# ---------------- REPORTS ----------------

if menu == "Reports":

    st.title("Prediction Reports")

    st.dataframe(df,use_container_width=True)

    col1,col2 = st.columns(2)

    with col1:

        csv = df.to_csv(index=False).encode("utf-8")

        st.download_button(
            "Download CSV",
            csv,
            "csat_history.csv"
        )

    with col2:

        excel_buffer = BytesIO()
        df.to_excel(excel_buffer,index=False)

        st.download_button(
            "Download Excel",
            excel_buffer.getvalue(),
            "csat_history.xlsx"
        )